"""VarysAgent — the cybersecurity sentinel for Guardian One.

Monitors security events across endpoints, network, and identity systems.
Detects threats via Sigma rules + anomaly detection, responds with
deterministic containment, and uses LLM for intelligent triage.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from guardian_one.core.audit import Severity
from guardian_one.core.base_agent import (
    AGENT_SYSTEM_PROMPTS,
    AgentReport,
    AgentStatus,
    BaseAgent,
)
from guardian_one.varys.detection.sigma_engine import SigmaEngine, SigmaMatch
from guardian_one.varys.detection.anomaly import AnomalyDetector
from guardian_one.varys.detection.risk_scoring import RiskScorer, RiskScore
from guardian_one.varys.response.containment import ContainmentEngine
from guardian_one.varys.response.alerting import AlertDispatcher
from guardian_one.varys.brain.llm_triage import LLMTriage, TriageResult
from guardian_one.varys.ingestion.auth_logs import AuthLogCollector

log = logging.getLogger(__name__)


# Register VARYS system prompt
AGENT_SYSTEM_PROMPTS["varys"] = (
    "You are VARYS, the cybersecurity sentinel within Guardian One. "
    "You monitor security events, detect threats, and recommend responses. "
    "Analyze events using MITRE ATT&CK framework. Be precise about severity, "
    "never exaggerate risk, and always recommend the least-disruptive effective response. "
    "Destructive actions require explicit human confirmation."
)


class AlertSeverity(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(Enum):
    NEW = "new"
    ACKNOWLEDGED = "acknowledged"
    ESCALATED = "escalated"
    DISMISSED = "dismissed"


@dataclass
class SecurityAlert:
    """A single security alert generated by VARYS."""
    id: str
    timestamp: str
    severity: AlertSeverity
    source: str
    title: str
    description: str
    mitre_technique: str = ""
    affected_host: str = ""
    affected_user: str = ""
    status: AlertStatus = AlertStatus.NEW
    llm_triage: TriageResult | None = None
    raw_event: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d = {
            "id": self.id,
            "timestamp": self.timestamp,
            "severity": self.severity.value,
            "source": self.source,
            "title": self.title,
            "description": self.description,
            "mitre_technique": self.mitre_technique,
            "affected_host": self.affected_host,
            "affected_user": self.affected_user,
            "status": self.status.value,
        }
        if self.llm_triage:
            d["llm_triage"] = self.llm_triage.to_dict()
        return d


class VarysAgent(BaseAgent):
    """Cybersecurity sentinel — monitors, detects, and responds to threats."""

    def __init__(self, config, audit) -> None:
        super().__init__(config, audit)
        self._alerts: list[SecurityAlert] = []
        self._alert_counter = 0
        self._sigma = SigmaEngine()
        self._anomaly = AnomalyDetector()
        self._risk = RiskScorer()
        self._containment = ContainmentEngine(audit=audit)
        self._alerter = AlertDispatcher()
        self._triage = LLMTriage()
        self._auth_collector = AuthLogCollector()
        self._events_processed = 0
        self._last_run: str = ""
        self._last_risk: RiskScore | None = None

    def initialize(self) -> None:
        """Load detection rules and initialize subsystems."""
        self._set_status(AgentStatus.RUNNING)
        self._sigma.load_rules()
        self._anomaly.initialize()
        self._set_status(AgentStatus.IDLE)
        self.log(
            "varys_initialized",
            details={
                "sigma_rules_loaded": self._sigma.rule_count,
                "anomaly_model": self._anomaly.model_name,
            },
        )

    def run(self) -> AgentReport:
        """Execute one security monitoring cycle."""
        self._set_status(AgentStatus.RUNNING)
        self._last_run = datetime.now(timezone.utc).isoformat()
        actions: list[str] = []
        new_alerts: list[SecurityAlert] = []

        # 1. Collect events from all ingestion sources
        events = self._collect_events()
        self._events_processed += len(events)

        # 2. Run detection on each event
        for event in events:
            # Sigma rule matching
            matches = self._sigma.match(event)
            for match in matches:
                alert = self._create_alert_from_sigma(match, event)
                new_alerts.append(alert)

            # Anomaly detection
            if self._anomaly.is_anomalous(event):
                alert = self._create_alert_from_anomaly(event)
                new_alerts.append(alert)

        # 3. Triage alerts with LLM (if available)
        for alert in new_alerts:
            if self.ai_enabled:
                triage_result = self._triage.triage_event(
                    self.think_quick, alert.to_dict()
                )
                alert.llm_triage = triage_result

        # 4. Execute response for high/critical alerts
        for alert in new_alerts:
            self._alerts.append(alert)
            response_action = self._execute_response(alert)
            if response_action:
                actions.append(response_action)

        # 5. Compute risk score (cached for side-effect-free report())
        risk = self._risk.compute(self._alerts)
        self._last_risk = risk

        self._set_status(AgentStatus.IDLE)
        return AgentReport(
            agent_name=self.name,
            status="ok",
            summary=(
                f"Processed {len(events)} events, "
                f"generated {len(new_alerts)} alerts. "
                f"Risk score: {risk.overall}/100 ({risk.trend})"
            ),
            actions_taken=actions,
            alerts=[a.title for a in new_alerts if a.severity in (
                AlertSeverity.HIGH, AlertSeverity.CRITICAL
            )],
            data={
                "events_processed": len(events),
                "new_alerts": len(new_alerts),
                "total_alerts": len(self._alerts),
                "risk_score": risk.to_dict(),
            },
        )

    def report(self) -> AgentReport:
        """Return current VARYS status without side effects."""
        risk = self._last_risk or RiskScore(
            overall=0, endpoint=0, network=0, identity=0, data=0, trend="stable"
        )
        active_alerts = [a for a in self._alerts if a.status == AlertStatus.NEW]
        return AgentReport(
            agent_name=self.name,
            status="ok",
            summary=(
                f"VARYS sentinel active. "
                f"{len(active_alerts)} open alerts, "
                f"{self._events_processed} events processed total. "
                f"Risk: {risk.overall}/100"
            ),
            data={
                "active_alerts": len(active_alerts),
                "total_alerts": len(self._alerts),
                "events_processed": self._events_processed,
                "risk_score": risk.to_dict(),
                "last_run": self._last_run,
            },
        )

    def get_rules(self) -> list[dict[str, Any]]:
        """Return all loaded Sigma detection rules."""
        return self._sigma.get_rules()

    def get_alert_by_id(self, alert_id: str) -> SecurityAlert | None:
        """Look up a single alert by ID."""
        for alert in self._alerts:
            if alert.id == alert_id:
                return alert
        return None

    # ── Alert management ──────────────────────────────────────────

    def get_alerts(
        self,
        severity: str | None = None,
        status: str | None = None,
        page: int = 1,
        limit: int = 20,
    ) -> list[dict[str, Any]]:
        """Return filtered, paginated alerts."""
        filtered = self._alerts
        if severity:
            filtered = [a for a in filtered if a.severity.value == severity]
        if status:
            filtered = [a for a in filtered if a.status.value == status]
        start = (page - 1) * limit
        return [a.to_dict() for a in filtered[start:start + limit]]

    def acknowledge_alert(self, alert_id: str) -> bool:
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.status = AlertStatus.ACKNOWLEDGED
                self.log("alert_acknowledged", details={"alert_id": alert_id})
                return True
        return False

    def escalate_alert(self, alert_id: str) -> bool:
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.status = AlertStatus.ESCALATED
                self.log(
                    "alert_escalated",
                    severity=Severity.WARNING,
                    details={"alert_id": alert_id},
                )
                return True
        return False

    def dismiss_alert(self, alert_id: str) -> bool:
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.status = AlertStatus.DISMISSED
                self.log("alert_dismissed", details={"alert_id": alert_id})
                return True
        return False

    # ── Private ────────────────────────────────────────────────

    def _collect_events(self) -> list[dict[str, Any]]:
        """Gather events from all ingestion sources."""
        events: list[dict[str, Any]] = []
        events.extend(self._auth_collector.collect())
        return events

    def _next_alert_id(self) -> str:
        self._alert_counter += 1
        return f"VARYS-{self._alert_counter:06d}"

    def _create_alert_from_sigma(
        self, match: SigmaMatch, event: dict[str, Any]
    ) -> SecurityAlert:
        return SecurityAlert(
            id=self._next_alert_id(),
            timestamp=datetime.now(timezone.utc).isoformat(),
            severity=AlertSeverity(match.level),
            source="sigma",
            title=match.title,
            description=match.description,
            mitre_technique=match.technique,
            affected_host=event.get("hostname", ""),
            affected_user=event.get("user", ""),
            raw_event=event,
        )

    def _create_alert_from_anomaly(
        self, event: dict[str, Any]
    ) -> SecurityAlert:
        return SecurityAlert(
            id=self._next_alert_id(),
            timestamp=datetime.now(timezone.utc).isoformat(),
            severity=AlertSeverity.MEDIUM,
            source="anomaly",
            title="Behavioral anomaly detected",
            description=f"Unusual activity from {event.get('user', 'unknown')}",
            affected_host=event.get("hostname", ""),
            affected_user=event.get("user", ""),
            raw_event=event,
        )

    def _execute_response(self, alert: SecurityAlert) -> str | None:
        """Execute automated response based on severity. Returns action taken."""
        if alert.severity == AlertSeverity.CRITICAL:
            isolated = False
            if alert.affected_host:
                isolated = self._containment.isolate_host(alert.affected_host)
            self._alerter.send_alert(alert, channels=["console", "email"])
            self.log(
                "auto_response_critical",
                severity=Severity.CRITICAL,
                details=alert.to_dict(),
                requires_review=True,
            )
            if isolated:
                return f"CRITICAL: Isolated {alert.affected_host}, sent alerts"
            return f"CRITICAL: Alert sent (no host to isolate)"
        elif alert.severity == AlertSeverity.HIGH:
            self._alerter.send_alert(alert, channels=["console"])
            self.log(
                "auto_response_high",
                severity=Severity.WARNING,
                details=alert.to_dict(),
            )
            return f"HIGH: Alert sent for {alert.title}"
        return None
