"""Notion remediation tracker sync — push verification results to Notion.

Syncs SecurityRemediationTracker data to the existing Notion database at:
    JTMDAI.com Security Remediation Tracker
    (page ID from NOTION_REMEDIATION_PAGE_ID or config)

Matches the Notion database schema:
    Aa Task | Category | Due Date | Last Checked | Notes | Severity | Status

Uses the same write-only, content-gated architecture as NotionSync
and NotionWebsiteDashboard.  Coordinates with Notion Agents
(Agency Operations Manager, Calendar Optimizer, Inbox Master,
CRM Agent, Inbox Organizer) by writing structured data they can consume.

Views supported:
    - Default view (table, all tasks sorted by severity)
    - Active Threats Board (filtered to non-complete tasks)
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from typing import Any

from guardian_one.core.audit import AuditLog, Severity
from guardian_one.core.security_remediation import (
    RemediationSeverity,
    RemediationStatus,
    SecurityRemediationTracker,
)
from guardian_one.integrations.notion_sync import (
    NotionSync,
    NotionPage,
    SyncResult,
    classify_content,
)


# Severity → Notion color mapping (matches the tracker's tag colors)
_SEVERITY_COLORS: dict[str, str] = {
    "Critical": "red",
    "High": "orange",
    "Medium": "yellow",
    "Low": "green",
    "Info": "blue",
}

# Category → Notion color mapping
_CATEGORY_COLORS: dict[str, str] = {
    "Email Security": "purple",
    "Cloudflare Config": "blue",
    "Webflow Platform": "green",
    "HTTP Security": "orange",
    "Infrastructure": "gray",
    "Brand Protection": "pink",
}

# Status → Notion color mapping
_STATUS_COLORS: dict[str, str] = {
    "Not Started": "red",
    "In Progress": "yellow",
    "Verified Complete": "green",
    "Blocked": "red",
}


class NotionRemediationSync:
    """Push security remediation status to the Notion tracker.

    Integrates with the existing Notion database page by pushing
    a summary dashboard and per-task status updates.  Does NOT
    modify the Notion database rows directly (respects write-only
    architecture) — instead pushes a verification report page.

    Works alongside Notion Agents:
        - Agency Operations Manager: sees remediation progress
        - Inbox Master: can route security alert emails to tracker
        - CRM Agent: tracks vendor security contacts

    Usage:
        sync = NotionRemediationSync(notion_sync, audit)
        result = sync.push_remediation_dashboard(tracker)
    """

    def __init__(self, notion_sync: NotionSync, audit: AuditLog) -> None:
        self._sync = notion_sync
        self._audit = audit
        self._parent_page_id: str = ""

    # ------------------------------------------------------------------
    # Parent page management
    # ------------------------------------------------------------------

    def _ensure_parent_page(self) -> str | None:
        """Create or return the 'Security Remediation' parent page."""
        if self._parent_page_id:
            return self._parent_page_id

        cache_key = "security_remediation"
        cached = self._sync._page_cache.get(cache_key)
        if cached:
            self._parent_page_id = cached.page_id
            return self._parent_page_id

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        children = [
            self._sync._callout(
                f"Security Remediation Hub | Last sync: {now}",
                "\U0001f6e1\ufe0f",
            ),
            self._sync._paragraph(
                "Active remediation tracker for jtmdai.com passive security audit findings. "
                "Auto-generated by Guardian One. Review each task daily and verify."
            ),
            self._sync._divider(),
        ]

        resp = self._sync._create_page(
            self._sync._root_page_id,
            "Security Remediation",
            icon_emoji="\U0001f6e1\ufe0f",
            children=children,
        )

        if resp.get("success") and resp.get("data"):
            page_id = resp["data"].get("id", "")
            self._parent_page_id = page_id
            self._sync._page_cache[cache_key] = NotionPage(
                page_id=page_id,
                title="Security Remediation",
                parent_id=self._sync._root_page_id,
                page_type="dashboard",
                last_synced=now,
                guardian_key=cache_key,
            )
            return page_id

        return None

    # ------------------------------------------------------------------
    # Dashboard push
    # ------------------------------------------------------------------

    def push_remediation_dashboard(
        self, tracker: SecurityRemediationTracker
    ) -> SyncResult:
        """Push the full remediation dashboard to Notion.

        Creates a page with:
            - Summary stats (completion %, critical open, overdue)
            - Task table grouped by severity
            - Agent ownership breakdown
            - Verification history for auto-checked tasks
        """
        start = time.monotonic()
        result = SyncResult(success=False)

        stats = tracker.summary_stats()
        tasks_data = tracker.notion_sync_data()
        text = json.dumps(tasks_data, default=str)

        if not classify_content(text, "agent_status"):
            result.errors.append("Content blocked by classification gate")
            return result

        parent_id = self._ensure_parent_page()
        if not parent_id:
            result.errors.append("Failed to create Security Remediation parent page")
            result.duration_ms = (time.monotonic() - start) * 1000
            return result

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Build the dashboard content
        completion_pct = stats["completion_pct"]
        completed = stats["completed"]
        total = stats["total_tasks"]
        remaining = stats["remaining"]
        critical_open = stats["critical_open"]

        # Status callout
        if critical_open > 0:
            callout_icon = "\U0001f534"
            callout_text = (
                f"{critical_open} CRITICAL open | "
                f"{completed}/{total} complete ({completion_pct}%) | "
                f"Last verified: {now}"
            )
        elif remaining > 0:
            callout_icon = "\U0001f7e1"
            callout_text = (
                f"{completed}/{total} complete ({completion_pct}%) | "
                f"{remaining} remaining | Last verified: {now}"
            )
        else:
            callout_icon = "\U0001f7e2"
            callout_text = (
                f"All {total} tasks verified complete! | "
                f"Last verified: {now}"
            )

        children = [
            self._sync._callout(callout_text, callout_icon),
        ]

        # Overdue warning
        overdue = tracker.overdue_tasks()
        if overdue:
            children.append(self._sync._callout(
                f"{len(overdue)} task(s) overdue — immediate attention required",
                "\u26a0\ufe0f",
            ))

        children.append(self._sync._heading("Summary", 2))
        children.append(self._sync._bulleted(
            f"Completion: {completed}/{total} ({completion_pct}%)"
        ))
        children.append(self._sync._bulleted(
            f"Critical open: {critical_open}"
        ))

        if overdue:
            children.append(self._sync._bulleted(
                f"Overdue: {len(overdue)} task(s)"
            ))

        # By category
        children.append(self._sync._divider())
        children.append(self._sync._heading("By Category", 2))
        for cat, count in stats["by_category"].items():
            cat_tasks = [t for t in tasks_data if t["category"] == cat]
            cat_complete = sum(
                1 for t in cat_tasks if t["status"] == "Verified Complete"
            )
            children.append(self._sync._bulleted(
                f"{cat}: {cat_complete}/{count} complete"
            ))

        # Task list by severity
        children.append(self._sync._divider())
        children.append(self._sync._heading("Active Threats Board", 2))

        for sev_label in ["Critical", "High", "Medium", "Low", "Info"]:
            sev_tasks = [t for t in tasks_data if t["severity"] == sev_label]
            if not sev_tasks:
                continue

            children.append(self._sync._heading(f"{sev_label} Priority", 3))

            for task in sev_tasks:
                status = task["status"]
                if status == "Verified Complete":
                    icon = "\u2705"
                elif status == "In Progress":
                    icon = "\U0001f7e1"
                elif status == "Blocked":
                    icon = "\U0001f534"
                else:
                    icon = "\u2b1c"

                task_line = f"{icon} [{task['category']}] {task['task']}"
                children.append(self._sync._bulleted(task_line))

                if task["last_checked"]:
                    children.append(self._sync._bulleted(
                        f"  Last checked: {task['last_checked']}"
                    ))

        # Agent ownership
        children.append(self._sync._divider())
        children.append(self._sync._heading("Agent Ownership", 2))
        agent_counts: dict[str, int] = {}
        for task in tasks_data:
            agent = task["owner_agent"]
            agent_counts[agent] = agent_counts.get(agent, 0) + 1
        for agent, count in sorted(agent_counts.items()):
            children.append(self._sync._bulleted(f"{agent}: {count} task(s)"))

        # Integration with Notion Agents
        children.append(self._sync._divider())
        children.append(self._sync._heading("Notion Agent Coordination", 2))
        children.append(self._sync._bulleted(
            "Agency Operations Manager: Monitors remediation progress"
        ))
        children.append(self._sync._bulleted(
            "Inbox Master: Routes security alert emails to tracker"
        ))
        children.append(self._sync._bulleted(
            "Calendar Optimizer: Schedules remediation review windows"
        ))

        children.append(self._sync._divider())
        children.append(self._sync._paragraph(f"Last synced: {now}"))

        # Upsert the page
        cache_key = "remediation_dashboard_jtmdai"
        cached = self._sync._page_cache.get(cache_key)

        if cached:
            resp = self._sync._replace_blocks(cached.page_id, children)
        else:
            resp = self._sync._create_page(
                parent_id,
                "JTMDAI.com — Remediation Status",
                icon_emoji="\U0001f6e1\ufe0f",
                children=children,
            )

        if resp.get("success") and resp.get("data"):
            page_id = resp["data"].get("id", "")
            if page_id and not cached:
                self._sync._page_cache[cache_key] = NotionPage(
                    page_id=page_id,
                    title="JTMDAI.com — Remediation Status",
                    parent_id=parent_id,
                    page_type="dashboard",
                    last_synced=now,
                    guardian_key=cache_key,
                )
            result.success = True
            result.pages_created = 0 if cached else 1
            result.pages_updated = 1 if cached else 0
            result.blocks_written = len(children)
        else:
            error = resp.get("error", "Unknown error")
            result.errors.append(error)
            self._audit.record(
                agent="notion_remediation_sync",
                action="sync_failed",
                severity=Severity.ERROR,
                details={"error": error},
            )

        result.duration_ms = (time.monotonic() - start) * 1000
        return result

    # ------------------------------------------------------------------
    # Verification report push
    # ------------------------------------------------------------------

    def push_verification_report(
        self,
        tracker: SecurityRemediationTracker,
        verification_results: list[dict[str, Any]],
    ) -> SyncResult:
        """Push a verification run report as a child page.

        Each verification run gets its own timestamped page under
        the remediation parent, showing what was checked and results.
        """
        start = time.monotonic()
        result = SyncResult(success=False)

        text = json.dumps(verification_results, default=str)
        if not classify_content(text, "agent_status"):
            result.errors.append("Content blocked by classification gate")
            return result

        parent_id = self._ensure_parent_page()
        if not parent_id:
            result.errors.append("Failed to create parent page")
            result.duration_ms = (time.monotonic() - start) * 1000
            return result

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        passed = sum(1 for v in verification_results if v.get("passed"))
        failed = sum(1 for v in verification_results if not v.get("passed"))

        children = [
            self._sync._callout(
                f"Verification Run: {passed} passed, {failed} failed | {now}",
                "\U0001f50d",
            ),
        ]

        for v in verification_results:
            icon = "\u2705" if v.get("passed") else "\u274c"
            children.append(self._sync._bulleted(
                f"{icon} {v.get('task_id', '?')}: {v.get('method', '?')} — "
                f"{v.get('evidence', 'no details')}"
            ))

        children.append(self._sync._divider())
        children.append(self._sync._paragraph(f"Generated: {now}"))

        resp = self._sync._create_page(
            parent_id,
            f"Verification Run — {now}",
            icon_emoji="\U0001f50d",
            children=children,
        )

        if resp.get("success") and resp.get("data"):
            result.success = True
            result.pages_created = 1
            result.blocks_written = len(children)
        else:
            error = resp.get("error", "Unknown error")
            result.errors.append(error)

        result.duration_ms = (time.monotonic() - start) * 1000
        return result
