"""Incident report generator — auto-generates security incident reports."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def generate_report(
    alert: dict[str, Any],
    triage: dict[str, Any] | None = None,
    actions_taken: list[str] | None = None,
) -> str:
    """Generate a Markdown incident report from an alert."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Security Incident Report",
        f"",
        f"**Generated**: {ts}",
        f"**Alert ID**: {alert.get('id', 'N/A')}",
        f"**Severity**: {alert.get('severity', 'unknown').upper()}",
        f"**Source**: {alert.get('source', 'unknown')}",
        f"",
        f"## Event Summary",
        f"",
        f"**Title**: {alert.get('title', 'No title')}",
        f"**Description**: {alert.get('description', 'No description')}",
        f"**MITRE Technique**: {alert.get('mitre_technique', 'N/A')}",
        f"**Affected Host**: {alert.get('affected_host', 'N/A')}",
        f"**Affected User**: {alert.get('affected_user', 'N/A')}",
    ]

    if triage:
        lines.extend([
            f"",
            f"## AI Triage Assessment",
            f"",
            f"- **Attack Type**: {triage.get('attack_type', 'unknown')}",
            f"- **Confidence**: {triage.get('confidence', 0):.0%}",
            f"- **Recommended Action**: {triage.get('recommended_action', 'N/A')}",
            f"- **Summary**: {triage.get('summary', '')}",
        ])

    if actions_taken:
        lines.extend([
            f"",
            f"## Actions Taken",
            f"",
        ])
        for action in actions_taken:
            lines.append(f"- {action}")

    lines.extend([
        f"",
        f"---",
        f"*Generated by VARYS — Guardian One Cybersecurity Sentinel*",
    ])

    return "\n".join(lines)
